comment.findAll=select c.id, c.text, c.post_id from blog.comments c where c.post_id = ? order by c.id desc
comment.findById=select c.id, c.text, c.post_id from blog.comments c where c.id = ?
comment.save=insert into blog.comments (text, post_id) values(?, ?)
comment.update=update blog.comments set text = ? where id = ?
comment.deleteById=delete from blog.comments where id = ?